// A bunch of words
?start: lines

lines: ( line )*
line: entity | attrib | atype | validator

entity: "E" ":" name ( "(" entity_names? ")" )? attribs? validators?
entity_names: entity_name ( "," entity_name )*
entity_name: name

attribs: "{" ( attrib  ( "," attrib )* "," )? "}"
attrib: "A" ":" name ( "(" attrib_names? ")" )? atype? validators?
attrib_names: attrib_name ( "," attrib_name )*
attrib_name: name 

atype: "T" ":" name ( "(" atype_names? ")" )?
atype_names: atype_name ( "," atype_name )*
atype_name: name

validators: "{" validator ( "," validator )* ","? "}"
validator: "V" ":" name ( "(" validator_names? ")" )?
validator_names: validator_name ( "," validator_name )*
validator_name: name

?name: CNAME

// imports WORD from library
%import common.WORD
%import common.ESCAPED_STRING -> STRING
%import common.NUMBER
%import common.CNAME

%import common.WS_INLINE
%import common.NEWLINE -> _NL

%ignore WS_INLINE
%ignore _NL